//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_Part()
        {
            this.Catalog_ManufacturerModelPart = new HashSet<Catalog_ManufacturerModelPart>();
            this.Catalog_ManufacturerModelProcedurePart = new HashSet<Catalog_ManufacturerModelProcedurePart>();
            this.Catalog_PartSupplier = new HashSet<Catalog_PartSupplier>();
            this.Catalog_PartWarehouse = new HashSet<Catalog_PartWarehouse>();
            this.Item_AssetProcedurePart = new HashSet<Item_AssetProcedurePart>();
            this.Item_WorkOrderEvent = new HashSet<Item_WorkOrderEvent>();
        }
    
        public System.Guid PartID { get; set; }
        public Nullable<System.Guid> PartCatagoryID { get; set; }
        public string PartCode { get; set; }
        public string PartDescription { get; set; }
        public decimal CostToBuy { get; set; }
        public decimal CostToSell { get; set; }
        public Nullable<bool> IsReferenceOnlyPart { get; set; }
        public Nullable<bool> IsIncludesGST { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public int SupplyTimeFromVendorDays { get; set; }
        public Nullable<int> SupplyTimeFromInternalWarehouse { get; set; }
        public Nullable<bool> IsSensitiveDate { get; set; }
        public Nullable<bool> IsSensitiveTemperature { get; set; }
        public string OriginalEquipmentManufacturerPartNumber { get; set; }
        public Nullable<decimal> DefaultMarkUp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelPart> Catalog_ManufacturerModelPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelProcedurePart> Catalog_ManufacturerModelProcedurePart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_PartSupplier> Catalog_PartSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_PartWarehouse> Catalog_PartWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_AssetProcedurePart> Item_AssetProcedurePart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderEvent> Item_WorkOrderEvent { get; set; }
    }
}
