//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EmployeeCompetency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_EmployeeCompetency()
        {
            this.Catalog_EmployeeCompetencyRegistration = new HashSet<Catalog_EmployeeCompetencyRegistration>();
        }
    
        public System.Guid EmployeeCompetencyID { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public System.Guid CompetencyTypeID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string Notes { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Dictionary_CompetencyType Dictionary_CompetencyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_EmployeeCompetencyRegistration> Catalog_EmployeeCompetencyRegistration { get; set; }
    }
}
