//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ManufacturerModelProcedureGuide
    {
        public System.Guid ModelProcedureGuideID { get; set; }
        public System.Guid ModelProcedureID { get; set; }
        public Nullable<System.Guid> ElectronicFormID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> ModelVersionID { get; set; }
    
        public virtual Catalog_ManufacturerModelProcedure Catalog_ManufacturerModelProcedure { get; set; }
    }
}
