//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ChargeRateTier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_ChargeRateTier()
        {
            this.Item_WorkOrderEvent = new HashSet<Item_WorkOrderEvent>();
        }
    
        public System.Guid ChargeRateTierID { get; set; }
        public string ChargeRateName { get; set; }
        public decimal ChargeRate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateValidFrom { get; set; }
        public Nullable<System.DateTime> DateValidTo { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
    
        public virtual Catalog_Vendor Catalog_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderEvent> Item_WorkOrderEvent { get; set; }
    }
}
