//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EmployeeLicenseRegistration
    {
        public System.Guid EmployeeLicenseRegistrationID { get; set; }
        public System.Guid EmployeeLicenseID { get; set; }
        public System.Guid FileTypeID { get; set; }
        public System.DateTime DateObtained { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime DateValidFrom { get; set; }
        public System.DateTime DateExpires { get; set; }
        public string Notes { get; set; }
        public string FileURI { get; set; }
    
        public virtual Catalog_EmployeeLicense Catalog_EmployeeLicense { get; set; }
        public virtual Dictionary_FileType Dictionary_FileType { get; set; }
    }
}
