//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EmployeeLicense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_EmployeeLicense()
        {
            this.Catalog_EmployeeLicenseRegistration = new HashSet<Catalog_EmployeeLicenseRegistration>();
            this.Catalog_EmployeeLicenseUnit = new HashSet<Catalog_EmployeeLicenseUnit>();
        }
    
        public System.Guid EmployeeLicenseID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid LicenseTypeID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string Notes { get; set; }
        public string LicenseNumber { get; set; }
        public string LicenseIssuedBy { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Dictionary_LicenseType Dictionary_LicenseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_EmployeeLicenseRegistration> Catalog_EmployeeLicenseRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_EmployeeLicenseUnit> Catalog_EmployeeLicenseUnit { get; set; }
    }
}
