//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ServiceSiteServiceDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_ServiceSiteServiceDepartment()
        {
            this.Catalog_Employee = new HashSet<Catalog_Employee>();
            this.Catalog_EmployeeServiceDepartments = new HashSet<Catalog_EmployeeServiceDepartments>();
            this.Configuration_ActorRoleServiceDepartment = new HashSet<Configuration_ActorRoleServiceDepartment>();
            this.Item_AssetProcedure = new HashSet<Item_AssetProcedure>();
            this.Item_Contract = new HashSet<Item_Contract>();
            this.Item_WorkOrder = new HashSet<Item_WorkOrder>();
        }
    
        public System.Guid ServiceDepartmentID { get; set; }
        public System.Guid ServiceSiteID { get; set; }
        public System.Guid DisciplineID { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
        public Nullable<System.Guid> CostCentreIDRecoverTo { get; set; }
        public string ServiceDepartmentName { get; set; }
        public Nullable<bool> IsCalibrationTeam { get; set; }
        public Nullable<bool> IsSweepTeam { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual Catalog_Address Catalog_Address { get; set; }
        public virtual Catalog_BusinessAreaDistrictCostCentre Catalog_BusinessAreaDistrictCostCentre { get; set; }
        public virtual Catalog_BusinessAreaDistrictCostCentre Catalog_BusinessAreaDistrictCostCentre1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_Employee> Catalog_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_EmployeeServiceDepartments> Catalog_EmployeeServiceDepartments { get; set; }
        public virtual Catalog_ServiceSite Catalog_ServiceSite { get; set; }
        public virtual Dictionary_Discipline Dictionary_Discipline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_ActorRoleServiceDepartment> Configuration_ActorRoleServiceDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_AssetProcedure> Item_AssetProcedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Contract> Item_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrder> Item_WorkOrder { get; set; }
    }
}
