//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ManufacturerModelProcedurePart
    {
        public System.Guid ModelProcedurePartsID { get; set; }
        public System.Guid ModelProcedureID { get; set; }
        public System.Guid PartID { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<bool> IsReplaceOnInspection { get; set; }
        public Nullable<System.Guid> ModelVersionID { get; set; }
    
        public virtual Catalog_ManufacturerModelProcedure Catalog_ManufacturerModelProcedure { get; set; }
        public virtual Catalog_Part Catalog_Part { get; set; }
    }
}
