//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ManufacturerModelFiles
    {
        public System.Guid ModelDocumentID { get; set; }
        public System.Guid ModelID { get; set; }
        public Nullable<System.Guid> ModelVersionID { get; set; }
        public System.Guid FileTypeID { get; set; }
        public string FileURI { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid EmployeeIDLastEdit { get; set; }
        public bool IsEnabled { get; set; }
        public string Version { get; set; }
        public bool IsArchived { get; set; }
        public bool IsUnverified { get; set; }
        public bool PublicationDate { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
    
        public virtual Catalog_ManufacturerModel Catalog_ManufacturerModel { get; set; }
        public virtual Dictionary_FileType Dictionary_FileType { get; set; }
    }
}
