//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ManufacturerModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_ManufacturerModel()
        {
            this.Catalog_ManufacturerModelCoverage = new HashSet<Catalog_ManufacturerModelCoverage>();
            this.Catalog_ManufacturerModelFiles = new HashSet<Catalog_ManufacturerModelFiles>();
            this.Catalog_ManufacturerModelPart = new HashSet<Catalog_ManufacturerModelPart>();
            this.Catalog_ManufacturerModelProcedure = new HashSet<Catalog_ManufacturerModelProcedure>();
        }
    
        public System.Guid ModelID { get; set; }
        public System.Guid ManufacturerID { get; set; }
        public System.Guid EquipmentTypeID { get; set; }
        public System.Guid RiskID { get; set; }
        public string ModelName { get; set; }
        public string ModelCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CostAverage { get; set; }
        public System.Guid DisciplineIDPrimary { get; set; }
        public Nullable<System.Guid> PowerTypeID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsTestEquipment { get; set; }
    
        public virtual Catalog_Manufacturer Catalog_Manufacturer { get; set; }
        public virtual Dictionary_Discipline Dictionary_Discipline { get; set; }
        public virtual Dictionary_EquipmentType Dictionary_EquipmentType { get; set; }
        public virtual Dictionary_PowerType Dictionary_PowerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelCoverage> Catalog_ManufacturerModelCoverage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelFiles> Catalog_ManufacturerModelFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelPart> Catalog_ManufacturerModelPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelProcedure> Catalog_ManufacturerModelProcedure { get; set; }
    }
}
