//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EmployeeCompetencyRegistration
    {
        public System.Guid EmployeeCompetencyRegistrationID { get; set; }
        public System.Guid EmployeeCompetencyID { get; set; }
        public System.DateTime DateObtained { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateValidFrom { get; set; }
        public System.DateTime DateExpires { get; set; }
        public string Notes { get; set; }
        public bool IsEnabled { get; set; }
        public System.Guid EmployeeIDCreatedBy { get; set; }
        public Nullable<System.Guid> EmployeeIDSupervisor { get; set; }
        public string Filename { get; set; }
    
        public virtual Catalog_EmployeeCompetency Catalog_EmployeeCompetency { get; set; }
    }
}
