//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ServiceSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_ServiceSite()
        {
            this.Catalog_Employee = new HashSet<Catalog_Employee>();
            this.Catalog_ServiceSiteServiceDepartment = new HashSet<Catalog_ServiceSiteServiceDepartment>();
        }
    
        public System.Guid ServiceSiteID { get; set; }
        public string ServiceSiteName { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
        public Nullable<System.Guid> FacilityID { get; set; }
        public Nullable<System.Guid> CostCentreIDRecoverTo { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual Catalog_Address Catalog_Address { get; set; }
        public virtual Catalog_BusinessAreaDistrictCostCentre Catalog_BusinessAreaDistrictCostCentre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_Employee> Catalog_Employee { get; set; }
        public virtual Dictionary_Facility Dictionary_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ServiceSiteServiceDepartment> Catalog_ServiceSiteServiceDepartment { get; set; }
    }
}
