//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EventResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_EventResponse()
        {
            this.Catalog_EventResponseRate = new HashSet<Catalog_EventResponseRate>();
            this.Item_WorkOrderEvent = new HashSet<Item_WorkOrderEvent>();
        }
    
        public System.Guid EventResponseID { get; set; }
        public string ResponseName { get; set; }
        public string ResponseCode { get; set; }
        public Nullable<bool> IsDefaultBillable { get; set; }
        public Nullable<bool> IsCorrective { get; set; }
        public Nullable<bool> IsAdministrative { get; set; }
        public Nullable<bool> IsMaintenance { get; set; }
        public Nullable<bool> IsCompliance { get; set; }
        public Nullable<bool> IsCalibration { get; set; }
        public Nullable<bool> IsObservation { get; set; }
        public Nullable<bool> IsFailure { get; set; }
        public Nullable<bool> IsInternalExceptionRaised { get; set; }
        public Nullable<bool> IsNonProductive { get; set; }
        public Nullable<bool> IsNonAttendance { get; set; }
        public Nullable<bool> IsOnlyBillThisPerWO { get; set; }
        public Nullable<bool> IsFixedFee { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_EventResponseRate> Catalog_EventResponseRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderEvent> Item_WorkOrderEvent { get; set; }
    }
}
