//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EmployeeRole
    {
        public System.Guid EmployeeRoleID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid RoleID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Notes { get; set; }
        public System.Guid EmployeeIDLastEditted { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Configuration_ActorRole Configuration_ActorRole { get; set; }
    }
}
