//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_Vendor()
        {
            this.Catalog_ChargeRateTier = new HashSet<Catalog_ChargeRateTier>();
            this.Catalog_PartSupplier = new HashSet<Catalog_PartSupplier>();
            this.Catalog_VendorAddress = new HashSet<Catalog_VendorAddress>();
            this.Catalog_VendorContact = new HashSet<Catalog_VendorContact>();
            this.Catalog_VendorPurchasingRules = new HashSet<Catalog_VendorPurchasingRules>();
            this.Item_Contract = new HashSet<Item_Contract>();
            this.Item_PurchaseOrder = new HashSet<Item_PurchaseOrder>();
            this.Item_PurchaseOrderRequest = new HashSet<Item_PurchaseOrderRequest>();
            this.Item_WorkOrder = new HashSet<Item_WorkOrder>();
            this.Item_WorkOrderAsset = new HashSet<Item_WorkOrderAsset>();
            this.Item_WorkOrderEvent = new HashSet<Item_WorkOrderEvent>();
        }
    
        public System.Guid VendorID { get; set; }
        public string VendorName { get; set; }
        public System.Guid AddressID { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
        public Nullable<int> AustralianBusinessNumber { get; set; }
        public Nullable<int> CustomerAccountNumber { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.Guid> VendorIDPrevious { get; set; }
        public Nullable<System.Guid> VendorIDParent { get; set; }
        public Nullable<decimal> OrderMinimumPremium { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ChargeRateTier> Catalog_ChargeRateTier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_PartSupplier> Catalog_PartSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_VendorAddress> Catalog_VendorAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_VendorContact> Catalog_VendorContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_VendorPurchasingRules> Catalog_VendorPurchasingRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Contract> Item_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_PurchaseOrder> Item_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_PurchaseOrderRequest> Item_PurchaseOrderRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrder> Item_WorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderAsset> Item_WorkOrderAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderEvent> Item_WorkOrderEvent { get; set; }
    }
}
