//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ManufacturerModelPart
    {
        public System.Guid ModelPartID { get; set; }
        public System.Guid ModelIID { get; set; }
        public System.Guid PartID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> ModelVersionID { get; set; }
    
        public virtual Catalog_ManufacturerModel Catalog_ManufacturerModel { get; set; }
        public virtual Catalog_Part Catalog_Part { get; set; }
    }
}
