//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_ManufacturerModelProcedure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_ManufacturerModelProcedure()
        {
            this.Catalog_ManufacturerModelProcedureGuide = new HashSet<Catalog_ManufacturerModelProcedureGuide>();
            this.Catalog_ManufacturerModelProcedurePart = new HashSet<Catalog_ManufacturerModelProcedurePart>();
        }
    
        public System.Guid ModelProcedureID { get; set; }
        public System.Guid ModelID { get; set; }
        public System.Guid ProcedureID { get; set; }
        public System.Guid PeriodID { get; set; }
        public int PeriodUnit { get; set; }
        public System.Guid PriorityID { get; set; }
        public Nullable<bool> RollForwardFromServiceStickerDate { get; set; }
        public int TimeToComplete { get; set; }
        public System.Guid PeriodIDOffset { get; set; }
        public int PeriodUnitOffset { get; set; }
        public Nullable<System.Guid> ModelVersionID { get; set; }
    
        public virtual Catalog_ManufacturerModel Catalog_ManufacturerModel { get; set; }
        public virtual Dictionary_Period Dictionary_Period { get; set; }
        public virtual Dictionary_Period Dictionary_Period1 { get; set; }
        public virtual Dictionary_Priority Dictionary_Priority { get; set; }
        public virtual Dictionary_Priority Dictionary_Priority1 { get; set; }
        public virtual Dictionary_Procedure Dictionary_Procedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelProcedureGuide> Catalog_ManufacturerModelProcedureGuide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelProcedurePart> Catalog_ManufacturerModelProcedurePart { get; set; }
    }
}
