//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_CustomerReporting
    {
        public System.Guid CustomerReportingElementID { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid ReportElementID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsDaily { get; set; }
        public Nullable<bool> IsWeekly { get; set; }
        public Nullable<bool> IsFortnightly { get; set; }
        public Nullable<bool> IsMonthly { get; set; }
        public Nullable<bool> IsCustomerCanRunAdhoc { get; set; }
        public Nullable<System.DateTime> DateLastRun { get; set; }
    
        public virtual Catalog_Customer Catalog_Customer { get; set; }
        public virtual Dictionary_ReportElement Dictionary_ReportElement { get; set; }
    }
}
