//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_CustomerBusinessAreaMapping
    {
        public System.Guid CustomerBusinessAreaMappingID { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid BusinessAreaID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual Catalog_BusinessArea Catalog_BusinessArea { get; set; }
        public virtual Catalog_Customer Catalog_Customer { get; set; }
    }
}
