//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Manufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_Manufacturer()
        {
            this.Catalog_ManufacturerModel = new HashSet<Catalog_ManufacturerModel>();
        }
    
        public System.Guid ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
        public System.Guid AddressID { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.Guid> ManufacturerIDPrevious { get; set; }
        public Nullable<System.Guid> ManufacturerIDParent { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModel> Catalog_ManufacturerModel { get; set; }
    }
}
