//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EmployeeServiceDepartments
    {
        public System.Guid EmployeeServiceDepartmentsID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid ServiceDepartmentID { get; set; }
        public Nullable<bool> IsReportedOn { get; set; }
        public Nullable<bool> IsDashboardSummary { get; set; }
        public Nullable<bool> IsExceptionReports { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Notes { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Catalog_ServiceSiteServiceDepartment Catalog_ServiceSiteServiceDepartment { get; set; }
    }
}
