//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EventResponseRate
    {
        public System.Guid EventResponseRateID { get; set; }
        public System.Guid EventResponseID { get; set; }
        public string RateName { get; set; }
        public decimal RateCharge { get; set; }
        public bool IsAfterHours { get; set; }
        public bool IsRateHourly { get; set; }
        public bool IsRateInstance { get; set; }
        public bool IsRefereceIDCostCentre { get; set; }
        public bool IsRefereceIDServiceDepartment { get; set; }
        public bool IsRefereceIDServiceSite { get; set; }
        public System.Guid ReferenceID { get; set; }
        public string Notes { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime DateValidFrom { get; set; }
        public System.DateTime DateValidTo { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Catalog_EventResponse Catalog_EventResponse { get; set; }
    }
}
