//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_BusinessAreaDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_BusinessAreaDistrict()
        {
            this.Catalog_BusinessAreaDistrictCostCentre = new HashSet<Catalog_BusinessAreaDistrictCostCentre>();
        }
    
        public System.Guid BusinessAreaDistrictID { get; set; }
        public System.Guid BusinessAreaID { get; set; }
        public string DistrictName { get; set; }
        public string DistrictCode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string Notes { get; set; }
    
        public virtual Catalog_BusinessArea Catalog_BusinessArea { get; set; }
        public virtual Catalog_BusinessAreaDistrict Catalog_BusinessAreaDistrict1 { get; set; }
        public virtual Catalog_BusinessAreaDistrict Catalog_BusinessAreaDistrict2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_BusinessAreaDistrictCostCentre> Catalog_BusinessAreaDistrictCostCentre { get; set; }
    }
}
