//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_EmployeeAccounts
    {
        public System.Guid EmployeeAccountsID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid CostCentreID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<decimal> ExpenditureLevelMinimum { get; set; }
        public Nullable<decimal> ExpenditureLevelMaximum { get; set; }
        public Nullable<System.Guid> ExpenditureGroup { get; set; }
        public string Notes { get; set; }
        public System.Guid EmployeeIDLastEditted { get; set; }
        public bool IsReportOn { get; set; }
        public bool IsPushNotificationsOn { get; set; }
    
        public virtual Catalog_BusinessAreaDistrictCostCentre Catalog_BusinessAreaDistrictCostCentre { get; set; }
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Catalog_Employee Catalog_Employee1 { get; set; }
    }
}
