//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_VendorAddress
    {
        public System.Guid VendorAddressID { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual Catalog_Address Catalog_Address { get; set; }
        public virtual Catalog_Vendor Catalog_Vendor { get; set; }
    }
}
