//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_BusinessArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_BusinessArea()
        {
            this.Catalog_BusinessAreaDistrict = new HashSet<Catalog_BusinessAreaDistrict>();
            this.Catalog_BusinessAreaDistrictCostCentre = new HashSet<Catalog_BusinessAreaDistrictCostCentre>();
            this.Catalog_CustomerBusinessAreaMapping = new HashSet<Catalog_CustomerBusinessAreaMapping>();
        }
    
        public System.Guid BusinessAreaID { get; set; }
        public string BusinessAreaCode { get; set; }
        public string BusinessAreaName { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_BusinessAreaDistrict> Catalog_BusinessAreaDistrict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_BusinessAreaDistrictCostCentre> Catalog_BusinessAreaDistrictCostCentre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_CustomerBusinessAreaMapping> Catalog_CustomerBusinessAreaMapping { get; set; }
    }
}
