//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_VendorContact
    {
        public System.Guid VendorContactsID { get; set; }
        public string ContactMeta { get; set; }
        public string Notes { get; set; }
        public bool IsPurchasingContact { get; set; }
        public bool IsTechnicalContact { get; set; }
        public bool IsEnabled { get; set; }
        public System.Guid ContactTypeID { get; set; }
        public System.Guid VendorID { get; set; }
    
        public virtual Catalog_Vendor Catalog_Vendor { get; set; }
        public virtual Dictionary_ContactType Dictionary_ContactType { get; set; }
    }
}
