//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalog_Customer()
        {
            this.Catalog_CustomerBusinessAreaMapping = new HashSet<Catalog_CustomerBusinessAreaMapping>();
            this.Catalog_CustomerReporting = new HashSet<Catalog_CustomerReporting>();
            this.Catalog_CustomerReportingCostCentreMapping = new HashSet<Catalog_CustomerReportingCostCentreMapping>();
            this.Item_WorkOrder = new HashSet<Item_WorkOrder>();
        }
    
        public System.Guid CustomerID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> IsBSQ { get; set; }
        public Nullable<bool> IsSDP { get; set; }
        public string LastViewMode { get; set; }
        public Nullable<bool> IsEmailNotificationsOn { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string ContactReturnAddress { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.Guid> DefaultCostCentre { get; set; }
        public string RegistrationCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_CustomerBusinessAreaMapping> Catalog_CustomerBusinessAreaMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_CustomerReporting> Catalog_CustomerReporting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_CustomerReportingCostCentreMapping> Catalog_CustomerReportingCostCentreMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrder> Item_WorkOrder { get; set; }
    }
}
