//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_VendorPurchasingRules
    {
        public System.Guid VendorPurchaseRuleID { get; set; }
        public System.Guid VendorID { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public System.Guid EmployeeID { get; set; }
        public bool IsMinimumOrder { get; set; }
        public bool IsFreight { get; set; }
        public Nullable<bool> IsDefaultCharge { get; set; }
        public decimal DefaultCharge { get; set; }
        public string RelatesToVendorPartNumber { get; set; }
    
        public virtual Catalog_Vendor Catalog_Vendor { get; set; }
    }
}
