//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_ElectronicForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuration_ElectronicForm()
        {
            this.Configuration_ElectronicFormTask = new HashSet<Configuration_ElectronicFormTask>();
        }
    
        public System.Guid ElectronicFormID { get; set; }
        public Nullable<System.Guid> ModelID { get; set; }
        public Nullable<System.Guid> EquipmentTypeID { get; set; }
        public string FormName { get; set; }
        public string Description { get; set; }
        public System.Guid EmployeeIDLastEditted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IfModelDoAboveType { get; set; }
        public Nullable<System.Guid> ElectronicFormIDSuperseededBy { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_ElectronicFormTask> Configuration_ElectronicFormTask { get; set; }
    }
}
