//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_ActorRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuration_ActorRole()
        {
            this.Catalog_EmployeeRole = new HashSet<Catalog_EmployeeRole>();
            this.Configuration_ActorRoleAccountManager = new HashSet<Configuration_ActorRoleAccountManager>();
            this.Configuration_ActorRoleSecurity = new HashSet<Configuration_ActorRoleSecurity>();
            this.Configuration_ActorRoleServiceDepartment = new HashSet<Configuration_ActorRoleServiceDepartment>();
        }
    
        public System.Guid RoleID { get; set; }
        public string RoleDescription { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<decimal> UtilisationTargetHoursDaily { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_EmployeeRole> Catalog_EmployeeRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_ActorRoleAccountManager> Configuration_ActorRoleAccountManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_ActorRoleSecurity> Configuration_ActorRoleSecurity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_ActorRoleServiceDepartment> Configuration_ActorRoleServiceDepartment { get; set; }
    }
}
