//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_ActorRoleAccountManager
    {
        public System.Guid RoleAccountManagerID { get; set; }
        public System.Guid RoleID { get; set; }
        public System.Guid CostCentreID { get; set; }
    
        public virtual Catalog_BusinessAreaDistrictCostCentre Catalog_BusinessAreaDistrictCostCentre { get; set; }
        public virtual Configuration_ActorRole Configuration_ActorRole { get; set; }
    }
}
