//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_ElectronicFormTaskRule
    {
        public System.Guid ElectronicFormTaskRuleID { get; set; }
        public System.Guid ElectronicFormTaskID { get; set; }
        public string RuleTargetParameterType { get; set; }
        public string RuleOperationType { get; set; }
        public bool IsPercentage { get; set; }
        public decimal UnitValue { get; set; }
        public bool IsPass { get; set; }
        public Nullable<System.Guid> IfPassGoToEFTaskID { get; set; }
        public Nullable<System.Guid> IfFailGoToEFTaskID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<decimal> BaseLineValue { get; set; }
        public Nullable<decimal> TaskCriteria { get; set; }
    
        public virtual Configuration_ElectronicFormTask Configuration_ElectronicFormTask { get; set; }
    }
}
