//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_ActorRoleSecurityElement
    {
        public System.Guid RoleSecurityElementID { get; set; }
        public System.Guid RoleSecurityID { get; set; }
        public System.Guid ControlItemID { get; set; }
        public bool CanAdd { get; set; }
        public bool CanEdit { get; set; }
        public bool CanDelete { get; set; }
        public bool CanView { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Notes { get; set; }
        public System.Guid EmployeeIDLastEditted { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Configuration_ActorRoleSecurity Configuration_ActorRoleSecurity { get; set; }
        public virtual Configuration_ControlItem Configuration_ControlItem { get; set; }
    }
}
