//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_ActorRoleServiceDepartment
    {
        public System.Guid RoleServiceDepartmentID { get; set; }
        public System.Guid RoleID { get; set; }
        public System.Guid ServiceDepartmentID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Notes { get; set; }
    
        public virtual Catalog_ServiceSiteServiceDepartment Catalog_ServiceSiteServiceDepartment { get; set; }
        public virtual Configuration_ActorRole Configuration_ActorRole { get; set; }
    }
}
