//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_PresentationGroup
    {
        public System.Guid PresentationGroupID { get; set; }
        public System.Guid PresentationID { get; set; }
        public int DisplayRank { get; set; }
        public string GroupName { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsSystemRequired { get; set; }
    
        public virtual Dictionary_Presentation Dictionary_Presentation { get; set; }
    }
}
