//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_Procedure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionary_Procedure()
        {
            this.Item_AssetProcedure = new HashSet<Item_AssetProcedure>();
            this.Item_WorkOrder = new HashSet<Item_WorkOrder>();
            this.Item_WorkOrderAsset = new HashSet<Item_WorkOrderAsset>();
        }
    
        public System.Guid ProcedureID { get; set; }
        public bool IsPMWorkOnly { get; set; }
        public string Procedure { get; set; }
        public string ProcedureCode { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> GuideSpecificationID { get; set; }
    
        public virtual Catalog_ManufacturerModelProcedure Catalog_ManufacturerModelProcedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_AssetProcedure> Item_AssetProcedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrder> Item_WorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderAsset> Item_WorkOrderAsset { get; set; }
    }
}
