//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_ElectronicFormGrouping
    {
        public System.Guid GroupingID { get; set; }
        public string GroupingName { get; set; }
        public Nullable<int> HeirachyPresented { get; set; }
        public string ImageIcon { get; set; }
    }
}
