//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_EquipmentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionary_EquipmentType()
        {
            this.Catalog_ManufacturerModel = new HashSet<Catalog_ManufacturerModel>();
        }
    
        public System.Guid EquipmentTypeID { get; set; }
        public string EquipmentTypeName { get; set; }
        public Nullable<System.Guid> DefaultRisk { get; set; }
        public Nullable<decimal> DefaultChargeRateFixed { get; set; }
        public Nullable<decimal> DefaultChargeRateHourly { get; set; }
        public string GlobalCode { get; set; }
        public System.Guid DisciplineIDPrimary { get; set; }
        public Nullable<int> LifeExpectancyYears { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModel> Catalog_ManufacturerModel { get; set; }
    }
}
