//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_WorkOrderStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionary_WorkOrderStatus()
        {
            this.Item_WorkOrder = new HashSet<Item_WorkOrder>();
            this.Item_WorkOrderAsset = new HashSet<Item_WorkOrderAsset>();
        }
    
        public System.Guid WorkOrderStatusID { get; set; }
        public string WorkOrderStatusName { get; set; }
        public string QuickKey { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsSystemRequired { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<bool> IsAvailableForClientRequest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrder> Item_WorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderAsset> Item_WorkOrderAsset { get; set; }
    }
}
