//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_Period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionary_Period()
        {
            this.Catalog_ManufacturerModelProcedure = new HashSet<Catalog_ManufacturerModelProcedure>();
            this.Catalog_ManufacturerModelProcedure1 = new HashSet<Catalog_ManufacturerModelProcedure>();
            this.Item_AssetCoverage = new HashSet<Item_AssetCoverage>();
            this.Item_AssetProcedure = new HashSet<Item_AssetProcedure>();
        }
    
        public System.Guid PeriodID { get; set; }
        public string PeriodName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelProcedure> Catalog_ManufacturerModelProcedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelProcedure> Catalog_ManufacturerModelProcedure1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_AssetCoverage> Item_AssetCoverage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_AssetProcedure> Item_AssetProcedure { get; set; }
    }
}
