//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_CoverageType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionary_CoverageType()
        {
            this.Catalog_ManufacturerModelCoverage = new HashSet<Catalog_ManufacturerModelCoverage>();
            this.Item_AssetCoverage = new HashSet<Item_AssetCoverage>();
        }
    
        public System.Guid CoverageTypeID { get; set; }
        public string CoverageName { get; set; }
        public bool IsPeriod { get; set; }
        public bool RequiresNotes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelCoverage> Catalog_ManufacturerModelCoverage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_AssetCoverage> Item_AssetCoverage { get; set; }
    }
}
