//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_FileType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionary_FileType()
        {
            this.Catalog_EmployeeLicenseRegistration = new HashSet<Catalog_EmployeeLicenseRegistration>();
            this.Catalog_ManufacturerModelFiles = new HashSet<Catalog_ManufacturerModelFiles>();
            this.Item_AssetFile = new HashSet<Item_AssetFile>();
        }
    
        public System.Guid FileTypeID { get; set; }
        public string FileType { get; set; }
        public string FileDescription { get; set; }
        public bool RequiresEncrypting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_EmployeeLicenseRegistration> Catalog_EmployeeLicenseRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_ManufacturerModelFiles> Catalog_ManufacturerModelFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_AssetFile> Item_AssetFile { get; set; }
    }
}
