//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_ContractStatus
    {
        public System.Guid ContractStatusID { get; set; }
        public string ContractStatusName { get; set; }
        public string Note { get; set; }
        public bool IsEnabled { get; set; }
    }
}
