//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_OperatingSystemPatch
    {
        public System.Guid OperatingSystemPatchID { get; set; }
        public System.Guid OperatingSystemID { get; set; }
        public string PatchCode { get; set; }
        public string Version { get; set; }
        public string PatchDescription { get; set; }
        public System.DateTime DateEntered { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DatePublication { get; set; }
        public string ReferenceURL { get; set; }
        public Nullable<System.Guid> OperatingSYstemPatchIDPrerequisit { get; set; }
    
        public virtual Dictionary_OperatingSystem Dictionary_OperatingSystem { get; set; }
    }
}
