//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary_PresentationGroupPanel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionary_PresentationGroupPanel()
        {
            this.Configuration_ControlItem = new HashSet<Configuration_ControlItem>();
            this.Configuration_ElectronicFormTask = new HashSet<Configuration_ElectronicFormTask>();
        }
    
        public System.Guid GroupPanelID { get; set; }
        public Nullable<System.Guid> PresentationGroupID { get; set; }
        public string PanelName { get; set; }
        public Nullable<int> DisplayRank { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_ControlItem> Configuration_ControlItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_ElectronicFormTask> Configuration_ElectronicFormTask { get; set; }
    }
}
