//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAMSEntities : DbContext
    {
        public GAMSEntities()
            : base("name=GAMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalog_Address> Catalog_Address { get; set; }
        public virtual DbSet<Catalog_BusinessArea> Catalog_BusinessArea { get; set; }
        public virtual DbSet<Catalog_BusinessAreaDistrict> Catalog_BusinessAreaDistrict { get; set; }
        public virtual DbSet<Catalog_BusinessAreaDistrictCostCentre> Catalog_BusinessAreaDistrictCostCentre { get; set; }
        public virtual DbSet<Catalog_ChargeRateTier> Catalog_ChargeRateTier { get; set; }
        public virtual DbSet<Catalog_Customer> Catalog_Customer { get; set; }
        public virtual DbSet<Catalog_CustomerBusinessAreaMapping> Catalog_CustomerBusinessAreaMapping { get; set; }
        public virtual DbSet<Catalog_CustomerReporting> Catalog_CustomerReporting { get; set; }
        public virtual DbSet<Catalog_CustomerReportingCostCentreMapping> Catalog_CustomerReportingCostCentreMapping { get; set; }
        public virtual DbSet<Catalog_Employee> Catalog_Employee { get; set; }
        public virtual DbSet<Catalog_EmployeeAccounts> Catalog_EmployeeAccounts { get; set; }
        public virtual DbSet<Catalog_EmployeeCompetency> Catalog_EmployeeCompetency { get; set; }
        public virtual DbSet<Catalog_EmployeeCompetencyRegistration> Catalog_EmployeeCompetencyRegistration { get; set; }
        public virtual DbSet<Catalog_EmployeeLicense> Catalog_EmployeeLicense { get; set; }
        public virtual DbSet<Catalog_EmployeeLicenseRegistration> Catalog_EmployeeLicenseRegistration { get; set; }
        public virtual DbSet<Catalog_EmployeeLicenseUnit> Catalog_EmployeeLicenseUnit { get; set; }
        public virtual DbSet<Catalog_EmployeeReportingExceptions> Catalog_EmployeeReportingExceptions { get; set; }
        public virtual DbSet<Catalog_EmployeeRole> Catalog_EmployeeRole { get; set; }
        public virtual DbSet<Catalog_EmployeeServiceDepartments> Catalog_EmployeeServiceDepartments { get; set; }
        public virtual DbSet<Catalog_EventResponse> Catalog_EventResponse { get; set; }
        public virtual DbSet<Catalog_EventResponseRate> Catalog_EventResponseRate { get; set; }
        public virtual DbSet<Catalog_Manufacturer> Catalog_Manufacturer { get; set; }
        public virtual DbSet<Catalog_ManufacturerModel> Catalog_ManufacturerModel { get; set; }
        public virtual DbSet<Catalog_ManufacturerModelCoverage> Catalog_ManufacturerModelCoverage { get; set; }
        public virtual DbSet<Catalog_ManufacturerModelFiles> Catalog_ManufacturerModelFiles { get; set; }
        public virtual DbSet<Catalog_ManufacturerModelPart> Catalog_ManufacturerModelPart { get; set; }
        public virtual DbSet<Catalog_ManufacturerModelProcedure> Catalog_ManufacturerModelProcedure { get; set; }
        public virtual DbSet<Catalog_ManufacturerModelProcedureGuide> Catalog_ManufacturerModelProcedureGuide { get; set; }
        public virtual DbSet<Catalog_ManufacturerModelProcedurePart> Catalog_ManufacturerModelProcedurePart { get; set; }
        public virtual DbSet<Catalog_ManufacturerModelVersion> Catalog_ManufacturerModelVersion { get; set; }
        public virtual DbSet<Catalog_Part> Catalog_Part { get; set; }
        public virtual DbSet<Catalog_PartSupplier> Catalog_PartSupplier { get; set; }
        public virtual DbSet<Catalog_PartWarehouse> Catalog_PartWarehouse { get; set; }
        public virtual DbSet<Catalog_ServiceSite> Catalog_ServiceSite { get; set; }
        public virtual DbSet<Catalog_ServiceSiteServiceDepartment> Catalog_ServiceSiteServiceDepartment { get; set; }
        public virtual DbSet<Catalog_Vendor> Catalog_Vendor { get; set; }
        public virtual DbSet<Catalog_VendorAddress> Catalog_VendorAddress { get; set; }
        public virtual DbSet<Catalog_VendorContact> Catalog_VendorContact { get; set; }
        public virtual DbSet<Catalog_VendorPurchasingRules> Catalog_VendorPurchasingRules { get; set; }
        public virtual DbSet<Configuration_ActorRole> Configuration_ActorRole { get; set; }
        public virtual DbSet<Configuration_ActorRoleAccountManager> Configuration_ActorRoleAccountManager { get; set; }
        public virtual DbSet<Configuration_ActorRoleSecurity> Configuration_ActorRoleSecurity { get; set; }
        public virtual DbSet<Configuration_ActorRoleSecurityElement> Configuration_ActorRoleSecurityElement { get; set; }
        public virtual DbSet<Configuration_ActorRoleServiceDepartment> Configuration_ActorRoleServiceDepartment { get; set; }
        public virtual DbSet<Configuration_Control> Configuration_Control { get; set; }
        public virtual DbSet<Configuration_ControlItem> Configuration_ControlItem { get; set; }
        public virtual DbSet<Configuration_ElectronicForm> Configuration_ElectronicForm { get; set; }
        public virtual DbSet<Configuration_ElectronicFormTask> Configuration_ElectronicFormTask { get; set; }
        public virtual DbSet<Configuration_ElectronicFormTaskRule> Configuration_ElectronicFormTaskRule { get; set; }
        public virtual DbSet<Dictioanry_DataType> Dictioanry_DataType { get; set; }
        public virtual DbSet<Dictionary_BSQConfiguration> Dictionary_BSQConfiguration { get; set; }
        public virtual DbSet<Dictionary_BTSCalibrationType> Dictionary_BTSCalibrationType { get; set; }
        public virtual DbSet<Dictionary_CompetencyType> Dictionary_CompetencyType { get; set; }
        public virtual DbSet<Dictionary_ContactType> Dictionary_ContactType { get; set; }
        public virtual DbSet<Dictionary_ContractLimitType> Dictionary_ContractLimitType { get; set; }
        public virtual DbSet<Dictionary_ContractStatus> Dictionary_ContractStatus { get; set; }
        public virtual DbSet<Dictionary_ContractType> Dictionary_ContractType { get; set; }
        public virtual DbSet<Dictionary_CoverageType> Dictionary_CoverageType { get; set; }
        public virtual DbSet<Dictionary_Decontamination> Dictionary_Decontamination { get; set; }
        public virtual DbSet<Dictionary_Discipline> Dictionary_Discipline { get; set; }
        public virtual DbSet<Dictionary_ElectronicFormControlType> Dictionary_ElectronicFormControlType { get; set; }
        public virtual DbSet<Dictionary_ElectronicFormGrouping> Dictionary_ElectronicFormGrouping { get; set; }
        public virtual DbSet<Dictionary_ElectronicFormOperationType> Dictionary_ElectronicFormOperationType { get; set; }
        public virtual DbSet<Dictionary_ElectronicFormRuleTarget> Dictionary_ElectronicFormRuleTarget { get; set; }
        public virtual DbSet<Dictionary_ElectronicFormValueType> Dictionary_ElectronicFormValueType { get; set; }
        public virtual DbSet<Dictionary_ElectronicFormValueUnit> Dictionary_ElectronicFormValueUnit { get; set; }
        public virtual DbSet<Dictionary_EquipmentCondition> Dictionary_EquipmentCondition { get; set; }
        public virtual DbSet<Dictionary_EquipmentContractIntent> Dictionary_EquipmentContractIntent { get; set; }
        public virtual DbSet<Dictionary_EquipmentType> Dictionary_EquipmentType { get; set; }
        public virtual DbSet<Dictionary_Facility> Dictionary_Facility { get; set; }
        public virtual DbSet<Dictionary_FacilityBuilding> Dictionary_FacilityBuilding { get; set; }
        public virtual DbSet<Dictionary_FacilityBuildingLocation> Dictionary_FacilityBuildingLocation { get; set; }
        public virtual DbSet<Dictionary_FileType> Dictionary_FileType { get; set; }
        public virtual DbSet<Dictionary_LicenseType> Dictionary_LicenseType { get; set; }
        public virtual DbSet<Dictionary_OperatingSystem> Dictionary_OperatingSystem { get; set; }
        public virtual DbSet<Dictionary_OperatingSystemPatch> Dictionary_OperatingSystemPatch { get; set; }
        public virtual DbSet<Dictionary_Ownership> Dictionary_Ownership { get; set; }
        public virtual DbSet<Dictionary_PartCatagory> Dictionary_PartCatagory { get; set; }
        public virtual DbSet<Dictionary_Period> Dictionary_Period { get; set; }
        public virtual DbSet<Dictionary_PowerType> Dictionary_PowerType { get; set; }
        public virtual DbSet<Dictionary_Presentation> Dictionary_Presentation { get; set; }
        public virtual DbSet<Dictionary_PresentationGroup> Dictionary_PresentationGroup { get; set; }
        public virtual DbSet<Dictionary_PresentationGroupPanel> Dictionary_PresentationGroupPanel { get; set; }
        public virtual DbSet<Dictionary_PresentationUserInputControlType> Dictionary_PresentationUserInputControlType { get; set; }
        public virtual DbSet<Dictionary_PresentationUserInputValue> Dictionary_PresentationUserInputValue { get; set; }
        public virtual DbSet<Dictionary_Priority> Dictionary_Priority { get; set; }
        public virtual DbSet<Dictionary_Procedure> Dictionary_Procedure { get; set; }
        public virtual DbSet<Dictionary_PurchaseStatus> Dictionary_PurchaseStatus { get; set; }
        public virtual DbSet<Dictionary_ReportElement> Dictionary_ReportElement { get; set; }
        public virtual DbSet<Dictionary_Risk> Dictionary_Risk { get; set; }
        public virtual DbSet<Dictionary_UnitOfMeasure> Dictionary_UnitOfMeasure { get; set; }
        public virtual DbSet<Dictionary_Warehouse> Dictionary_Warehouse { get; set; }
        public virtual DbSet<Dictionary_WorkOrderFailure> Dictionary_WorkOrderFailure { get; set; }
        public virtual DbSet<Dictionary_WorkOrderStatus> Dictionary_WorkOrderStatus { get; set; }
        public virtual DbSet<Dictionary_WorkOrderType> Dictionary_WorkOrderType { get; set; }
        public virtual DbSet<Item_Asset> Item_Asset { get; set; }
        public virtual DbSet<Item_AssetControlItemValue> Item_AssetControlItemValue { get; set; }
        public virtual DbSet<Item_AssetCoverage> Item_AssetCoverage { get; set; }
        public virtual DbSet<Item_AssetFile> Item_AssetFile { get; set; }
        public virtual DbSet<Item_AssetHistory> Item_AssetHistory { get; set; }
        public virtual DbSet<Item_AssetProcedure> Item_AssetProcedure { get; set; }
        public virtual DbSet<Item_AssetProcedurePart> Item_AssetProcedurePart { get; set; }
        public virtual DbSet<Item_Contract> Item_Contract { get; set; }
        public virtual DbSet<Item_ContractAsset> Item_ContractAsset { get; set; }
        public virtual DbSet<Item_ContractControlItemValue> Item_ContractControlItemValue { get; set; }
        public virtual DbSet<Item_ContractFile> Item_ContractFile { get; set; }
        public virtual DbSet<Item_ContractLimit> Item_ContractLimit { get; set; }
        public virtual DbSet<Item_ContractRates> Item_ContractRates { get; set; }
        public virtual DbSet<Item_DeliveryAdvice> Item_DeliveryAdvice { get; set; }
        public virtual DbSet<Item_DeliveryAdviceItem> Item_DeliveryAdviceItem { get; set; }
        public virtual DbSet<Item_PurchaseOrder> Item_PurchaseOrder { get; set; }
        public virtual DbSet<Item_PurchaseOrderControlItemValue> Item_PurchaseOrderControlItemValue { get; set; }
        public virtual DbSet<Item_PurchaseOrderHistory> Item_PurchaseOrderHistory { get; set; }
        public virtual DbSet<Item_PurchaseOrderInvoice> Item_PurchaseOrderInvoice { get; set; }
        public virtual DbSet<Item_PurchaseOrderNotes> Item_PurchaseOrderNotes { get; set; }
        public virtual DbSet<Item_PurchaseOrderRequest> Item_PurchaseOrderRequest { get; set; }
        public virtual DbSet<Item_WorkOrder> Item_WorkOrder { get; set; }
        public virtual DbSet<Item_WorkOrderAsset> Item_WorkOrderAsset { get; set; }
        public virtual DbSet<Item_WorkOrderControlItemValue> Item_WorkOrderControlItemValue { get; set; }
        public virtual DbSet<Item_WorkOrderEvent> Item_WorkOrderEvent { get; set; }
        public virtual DbSet<Item_WorkOrderEventControlItemValue> Item_WorkOrderEventControlItemValue { get; set; }
        public virtual DbSet<Item_WorkOrderEventInvoice> Item_WorkOrderEventInvoice { get; set; }
        public virtual DbSet<Item_WorkOrderEventWarehouseTransaction> Item_WorkOrderEventWarehouseTransaction { get; set; }
        public virtual DbSet<Item_WorkOrderFile> Item_WorkOrderFile { get; set; }
        public virtual DbSet<Item_WorkOrderHistory> Item_WorkOrderHistory { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<xxItem_AssetLegacy> xxItem_AssetLegacy { get; set; }
        public virtual DbSet<Dictionary_EquipmentStatus> Dictionary_EquipmentStatus { get; set; }
    }
}
