//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_WorkOrder()
        {
            this.Catalog_Employee = new HashSet<Catalog_Employee>();
            this.Item_DeliveryAdviceItem = new HashSet<Item_DeliveryAdviceItem>();
            this.Item_WorkOrderAsset = new HashSet<Item_WorkOrderAsset>();
            this.Item_WorkOrderControlItemValue = new HashSet<Item_WorkOrderControlItemValue>();
            this.Item_WorkOrderEvent = new HashSet<Item_WorkOrderEvent>();
            this.Item_WorkOrderFile = new HashSet<Item_WorkOrderFile>();
            this.Item_WorkOrderHistory = new HashSet<Item_WorkOrderHistory>();
        }
    
        public System.Guid WorkOrderID { get; set; }
        public int WorkOrderReferenceNumber { get; set; }
        public string ClientReferenceNumber { get; set; }
        public string WorkGroupReferenceNumber { get; set; }
        public Nullable<System.Guid> ServiceDepartmentID { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
        public Nullable<System.Guid> FacilityID { get; set; }
        public Nullable<System.Guid> FacilityBuildingID { get; set; }
        public Nullable<System.Guid> FacilityBuildingLocationID { get; set; }
        public Nullable<System.Guid> ProcedureID { get; set; }
        public Nullable<System.Guid> PriorityID { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.Guid> WorkOrderTypeID { get; set; }
        public Nullable<System.Guid> WorkOrderStatusID { get; set; }
        public Nullable<System.DateTime> DateWorkOrderStatus { get; set; }
        public Nullable<System.Guid> WorkOrderFailureID { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsBillable { get; set; }
        public Nullable<decimal> ChargeNotToExceed { get; set; }
        public Nullable<decimal> ChargeWorkOrderValue { get; set; }
        public Nullable<decimal> ChargeTotalProcessed { get; set; }
        public Nullable<System.DateTime> ChargeLastProcessed { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string RequestText { get; set; }
        public Nullable<bool> IsWarranty { get; set; }
        public Nullable<bool> IsContract { get; set; }
        public Nullable<System.Guid> DecontaminationIDOnPresentation { get; set; }
        public Nullable<int> TotalEquipmentDowntime { get; set; }
    
        public virtual Catalog_Customer Catalog_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_Employee> Catalog_Employee { get; set; }
        public virtual Catalog_Employee Catalog_Employee1 { get; set; }
        public virtual Catalog_ServiceSiteServiceDepartment Catalog_ServiceSiteServiceDepartment { get; set; }
        public virtual Catalog_Vendor Catalog_Vendor { get; set; }
        public virtual Dictionary_Decontamination Dictionary_Decontamination { get; set; }
        public virtual Dictionary_Facility Dictionary_Facility { get; set; }
        public virtual Dictionary_FacilityBuilding Dictionary_FacilityBuilding { get; set; }
        public virtual Dictionary_FacilityBuildingLocation Dictionary_FacilityBuildingLocation { get; set; }
        public virtual Dictionary_Procedure Dictionary_Procedure { get; set; }
        public virtual Dictionary_WorkOrderFailure Dictionary_WorkOrderFailure { get; set; }
        public virtual Dictionary_WorkOrderStatus Dictionary_WorkOrderStatus { get; set; }
        public virtual Dictionary_WorkOrderType Dictionary_WorkOrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_DeliveryAdviceItem> Item_DeliveryAdviceItem { get; set; }
        public virtual Item_WorkOrder Item_WorkOrder1 { get; set; }
        public virtual Item_WorkOrder Item_WorkOrder2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderAsset> Item_WorkOrderAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderControlItemValue> Item_WorkOrderControlItemValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderEvent> Item_WorkOrderEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderFile> Item_WorkOrderFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderHistory> Item_WorkOrderHistory { get; set; }
    }
}
