//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_AssetProcedure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_AssetProcedure()
        {
            this.Item_AssetProcedurePart = new HashSet<Item_AssetProcedurePart>();
        }
    
        public System.Guid AssetProcedureID { get; set; }
        public System.Guid AssetID { get; set; }
        public System.Guid ProcedureID { get; set; }
        public System.Guid PeriodID { get; set; }
        public int PeriodUnit { get; set; }
        public System.Guid PriorityID { get; set; }
        public Nullable<System.Guid> ServiceDepartmentID { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
        public Nullable<bool> RollForwardFromServiceStickerDate { get; set; }
        public Nullable<System.DateTime> DateNextDue { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.Guid> ContractIDCoveredBy { get; set; }
        public Nullable<int> TimeToComplete { get; set; }
        public Nullable<System.Guid> ModelProcedureIDInheritance { get; set; }
        public string Notes { get; set; }
    
        public virtual Catalog_ServiceSiteServiceDepartment Catalog_ServiceSiteServiceDepartment { get; set; }
        public virtual Dictionary_Period Dictionary_Period { get; set; }
        public virtual Dictionary_Priority Dictionary_Priority { get; set; }
        public virtual Dictionary_Procedure Dictionary_Procedure { get; set; }
        public virtual Item_Asset Item_Asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_AssetProcedurePart> Item_AssetProcedurePart { get; set; }
    }
}
