//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_AssetCoverage
    {
        public System.Guid AssetCoverageID { get; set; }
        public System.Guid AssetID { get; set; }
        public System.Guid CoverageTypeID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> TermValue { get; set; }
        public Nullable<System.Guid> PeriodID { get; set; }
        public Nullable<System.DateTime> DateAbsolute { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<System.Guid> ModelCoverageIDInheritance { get; set; }
    
        public virtual Dictionary_CoverageType Dictionary_CoverageType { get; set; }
        public virtual Dictionary_Period Dictionary_Period { get; set; }
        public virtual Item_Asset Item_Asset { get; set; }
    }
}
