//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_ContractRates
    {
        public System.Guid ContractRateID { get; set; }
        public System.Guid ContractID { get; set; }
        public string RateName { get; set; }
        public bool IncludesLabour { get; set; }
        public bool IncludesParts { get; set; }
        public bool IncludesTravel { get; set; }
        public bool IncludesFreight { get; set; }
        public bool IsVariable { get; set; }
        public bool IsDefault { get; set; }
        public bool IncludedInContract { get; set; }
        public decimal RateValue { get; set; }
    }
}
