//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_DeliveryAdviceItem
    {
        public System.Guid DeliveryAdviceItemID { get; set; }
        public System.Guid DeliveryAdviceID { get; set; }
        public Nullable<System.Guid> WorkOrderID { get; set; }
        public Nullable<System.Guid> WorkOrderEventID { get; set; }
        public string ItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> QuantitySent { get; set; }
        public Nullable<decimal> QuantityReceived { get; set; }
        public Nullable<System.Guid> UnitOfMeasureID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> EmployeeIDLastEditted { get; set; }
        public Nullable<System.Guid> DecontaminationID { get; set; }
        public string Reason { get; set; }
        public string VendorInstructions { get; set; }
        public Nullable<bool> IsException { get; set; }
        public string Notes { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Dictionary_Decontamination Dictionary_Decontamination { get; set; }
        public virtual Dictionary_UnitOfMeasure Dictionary_UnitOfMeasure { get; set; }
        public virtual Item_WorkOrderEvent Item_WorkOrderEvent { get; set; }
        public virtual Item_WorkOrder Item_WorkOrder { get; set; }
        public virtual Item_WorkOrderEvent Item_WorkOrderEvent1 { get; set; }
    }
}
