//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_WorkOrderFile
    {
        public System.Guid WorkOrderFileID { get; set; }
        public System.Guid WorkOrderID { get; set; }
        public string FileURI { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid EmployeeID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<bool> IsCalibrationReport { get; set; }
        public Nullable<bool> IsServiceReport { get; set; }
        public Nullable<bool> IsComplianceReport { get; set; }
        public Nullable<bool> IsPrivateViewingOnly { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Item_WorkOrder Item_WorkOrder { get; set; }
    }
}
