//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_AssetHistory
    {
        public System.Guid AssetHistoryID { get; set; }
        public System.Guid AssetID { get; set; }
        public string ColumnName { get; set; }
        public string OldValue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid EmployeeID { get; set; }
        public string Notes { get; set; }
        public System.Guid RelatesToControlItemID { get; set; }
        public Nullable<System.Guid> ExceptionID { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Configuration_ControlItem Configuration_ControlItem { get; set; }
        public virtual Item_Asset Item_Asset { get; set; }
    }
}
