//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_Contract()
        {
            this.Item_ContractAsset = new HashSet<Item_ContractAsset>();
            this.Item_ContractControlItemValue = new HashSet<Item_ContractControlItemValue>();
            this.Item_ContractFile = new HashSet<Item_ContractFile>();
            this.Item_ContractLimit = new HashSet<Item_ContractLimit>();
        }
    
        public System.Guid ContractID { get; set; }
        public System.Guid VendorID { get; set; }
        public System.Guid ContractTypeID { get; set; }
        public System.Guid ContractStatusID { get; set; }
        public System.DateTime DateContractStatus { get; set; }
        public int ContractControlNumber { get; set; }
        public Nullable<int> TermNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateEffectiveStart { get; set; }
        public Nullable<System.DateTime> DateEffectiveEnd { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> EmployeeIDLastEdit { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public string Notes { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<System.Guid> ServiceDepartmentID { get; set; }
        public Nullable<decimal> ChargeTotal { get; set; }
        public Nullable<System.Guid> PaymentScheme { get; set; }
        public Nullable<System.DateTime> DatePaymentInitial { get; set; }
        public Nullable<System.DateTime> DatePaymentFinal { get; set; }
        public Nullable<decimal> WarningNotificationSpendingPercentage { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Catalog_Employee Catalog_Employee1 { get; set; }
        public virtual Catalog_ServiceSiteServiceDepartment Catalog_ServiceSiteServiceDepartment { get; set; }
        public virtual Catalog_Vendor Catalog_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ContractAsset> Item_ContractAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ContractControlItemValue> Item_ContractControlItemValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ContractFile> Item_ContractFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_ContractLimit> Item_ContractLimit { get; set; }
    }
}
