//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_WorkOrderEventWarehouseTransaction
    {
        public System.Guid WorkOrderEventWarehouseTransactionID { get; set; }
        public System.Guid WorkOrderEventID { get; set; }
        public int QuantitySent { get; set; }
        public int QuantityReceived { get; set; }
        public System.DateTime DateStickerPrinted { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public Nullable<System.Guid> DeliveryAdviceID { get; set; }
        public bool IsVoided { get; set; }
        public bool IsReversed { get; set; }
        public System.Guid EmployeeIDSentTo { get; set; }
        public Nullable<System.Guid> ServiceSiteIDSendTo { get; set; }
        public string Notes { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Catalog_Employee Catalog_Employee1 { get; set; }
        public virtual Item_DeliveryAdvice Item_DeliveryAdvice { get; set; }
        public virtual Item_WorkOrderEvent Item_WorkOrderEvent { get; set; }
    }
}
