//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_PurchaseOrderRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_PurchaseOrderRequest()
        {
            this.Item_WorkOrderEvent = new HashSet<Item_WorkOrderEvent>();
            this.Item_WorkOrderEventInvoice = new HashSet<Item_WorkOrderEventInvoice>();
        }
    
        public System.Guid RequestID { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
        public string VendorInstructions { get; set; }
        public int RequestReferenceNumber { get; set; }
        public Nullable<System.Guid> PurchaseOrderID { get; set; }
        public Nullable<System.Guid> EmployeeIDResponsible { get; set; }
        public Nullable<System.Guid> EmployeeIDApproval { get; set; }
        public Nullable<System.DateTime> DateApprovalConfirmed { get; set; }
        public Nullable<System.DateTime> DateApprovalRejected { get; set; }
        public string ApprovalNotes { get; set; }
        public Nullable<System.Guid> PurchaseStatusID { get; set; }
        public string DatePurchaseStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Catalog_Address Catalog_Address { get; set; }
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Catalog_Employee Catalog_Employee1 { get; set; }
        public virtual Catalog_Vendor Catalog_Vendor { get; set; }
        public virtual Dictionary_PurchaseStatus Dictionary_PurchaseStatus { get; set; }
        public virtual Item_PurchaseOrder Item_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderEvent> Item_WorkOrderEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_WorkOrderEventInvoice> Item_WorkOrderEventInvoice { get; set; }
    }
}
