//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_AssetFile
    {
        public System.Guid AssetFileID { get; set; }
        public Nullable<System.Guid> AssetID { get; set; }
        public System.Guid FileTypeID { get; set; }
        public string FileURI { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsPrivateViewOnly { get; set; }
    
        public virtual Dictionary_FileType Dictionary_FileType { get; set; }
        public virtual Item_Asset Item_Asset { get; set; }
    }
}
