//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_AssetProcedurePart
    {
        public System.Guid AssetProcedurePartID { get; set; }
        public System.Guid AssetProcedureID { get; set; }
        public System.Guid PartID { get; set; }
        public decimal Quantity { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid EmployeeID { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Catalog_Part Catalog_Part { get; set; }
        public virtual Item_AssetProcedure Item_AssetProcedure { get; set; }
    }
}
