//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_WorkOrderEventInvoice
    {
        public System.Guid WorkOrderEventInvoiceID { get; set; }
        public System.Guid WorkOrderEventID { get; set; }
        public System.Guid RequestID { get; set; }
        public System.Guid PurchaseOrderID { get; set; }
        public Nullable<decimal> InvoicedQuantity { get; set; }
        public Nullable<decimal> InvoicedValue { get; set; }
        public Nullable<System.DateTime> DateInvoiced { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public Nullable<bool> IsCredit { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Item_PurchaseOrder Item_PurchaseOrder { get; set; }
        public virtual Item_PurchaseOrderRequest Item_PurchaseOrderRequest { get; set; }
        public virtual Item_WorkOrderEvent Item_WorkOrderEvent { get; set; }
    }
}
