//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_PurchaseOrderNotes
    {
        public System.Guid PurchaseOrderNotesID { get; set; }
        public System.Guid PurchaseOrderID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid EmployeeIDCreated { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> EmployeeIDAttentionTo { get; set; }
        public Nullable<System.Guid> PurchaseOrderNotesIDRespondedTo { get; set; }
    
        public virtual Catalog_Employee Catalog_Employee { get; set; }
        public virtual Item_PurchaseOrder Item_PurchaseOrder { get; set; }
    }
}
