//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxItem_AssetLegacy
    {
        public System.Guid AssetID { get; set; }
        public string AssetNumberPrimary { get; set; }
        public string AssetNumberSecondary { get; set; }
        public System.Guid CostCentreOwner { get; set; }
        public System.Guid CostCentreManaged { get; set; }
        public Nullable<System.Guid> ModelID { get; set; }
        public Nullable<System.Guid> ServiceDepartmentID { get; set; }
        public string AssetNumberFinancial { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.Guid> FacilityID { get; set; }
        public Nullable<System.Guid> FacilityBuildingID { get; set; }
        public Nullable<System.Guid> FacilityBuildingLocationID { get; set; }
        public Nullable<System.DateTime> DatePhysicalLocation { get; set; }
        public Nullable<System.Guid> RiskIDClientElected { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
        public Nullable<System.Guid> OwnershipID { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<decimal> PurchaseOrderCost { get; set; }
        public Nullable<bool> IsPurchaseOrderCostEstimate { get; set; }
        public Nullable<System.Guid> EquipmentConditionID { get; set; }
        public Nullable<System.DateTime> DateCondition { get; set; }
        public Nullable<System.Guid> EquipmentStatusID { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<System.DateTime> DateInservice { get; set; }
        public Nullable<System.DateTime> DateCondemned { get; set; }
        public Nullable<System.Guid> ItemIDParent { get; set; }
        public Nullable<System.Guid> ServiceDepartmentIDGeneral { get; set; }
        public Nullable<System.Guid> ServiceDepartmentIDPreventive { get; set; }
        public Nullable<System.Guid> PrimaryCarerType { get; set; }
        public Nullable<System.Guid> VendorIDPrimaryCarer { get; set; }
        public Nullable<System.Guid> BSQConfigurationID { get; set; }
        public Nullable<System.Guid> BTSCalibrationTypeID { get; set; }
        public string ISOperatingSystem { get; set; }
        public string ISWLAN { get; set; }
        public string ISPrimaryAppSoftwareRevision { get; set; }
        public string ISPrimaryMBFirmwareRevision { get; set; }
        public string ISPrimaryWirelessCardFirmwareRevision { get; set; }
        public string ISVLAN1 { get; set; }
        public string ISVLAN2 { get; set; }
        public Nullable<bool> ieMRProduction { get; set; }
        public Nullable<System.DateTime> DateLastServiceLabelDate { get; set; }
        public Nullable<System.Guid> EquipmentContractIntentID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
