//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADR
    {
        public string TYPE { get; set; }
        public string CODE { get; set; }
        public string ADD_LINE_1 { get; set; }
        public string ADD_LINE_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string CONTACT_1 { get; set; }
        public string CONT_1_PH { get; set; }
        public string CONT_1_EXT { get; set; }
        public string CONTACT_2 { get; set; }
        public string CONT_2_PH { get; set; }
        public string CONT_2_EXT { get; set; }
        public string NOTES { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string FACILITY { get; set; }
        public string SUPPLIER_NUM { get; set; }
        public string TERMS { get; set; }
        public string FSRSupplierOldNumber { get; set; }
        public string FSRSupplierNewNumber { get; set; }
    }
}
