//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIMSDatabaseEntities1 : DbContext
    {
        public AIMSDatabaseEntities1()
            : base("name=AIMSDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADR> ADRs { get; set; }       
        public virtual DbSet<DIR_ADR> DIR_ADR { get; set; }
        public virtual DbSet<LINE_ITEM> LINE_ITEM { get; set; }
        public virtual DbSet<PO> POes { get; set; }
        public virtual DbSet<EQU> EQUs { get; set; }
        public virtual DbSet<PRT> PRTs { get; set; }
        public virtual DbSet<WCM> WCMs { get; set; }
        public virtual DbSet<WCT> WCTs { get; set; }
        public virtual DbSet<WKO> WKOes { get; set; }
    }
}
