//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BNAEntities : DbContext
    {
        public BNAEntities()
            : base("name=BNAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeliveryAdvice_Shipping> DeliveryAdvice_Shipping { get; set; }
        public virtual DbSet<DeliveryAdvice_item1> DeliveryAdvice_item1 { get; set; }
    }
}
