//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAdvice_Shipping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryAdvice_Shipping()
        {
            this.DeliveryAdvice_item1 = new HashSet<DeliveryAdvice_item1>();
        }
    
        public int DeliveryNo { get; set; }
        public string FromName { get; set; }
        public string FromAddress { get; set; }
        public string ToName { get; set; }
        public string ToAddress { get; set; }
        public string ConnoteNum { get; set; }
        public string Courier { get; set; }
        public string date { get; set; }
        public string DeliveryReasonNum { get; set; }
        public string Notes { get; set; }
        public string EMPCode { get; set; }
        public string EMPName { get; set; }
        public string RECV_DATE { get; set; }
        public string ACCESORIES { get; set; }
        public string FACILITY { get; set; }
        public string TYPE { get; set; }
        public Nullable<bool> ISEDITABLE { get; set; }
        public string REAL_CC { get; set; }
        public string RECEIVED_BY { get; set; }
        public System.DateTime LAST_PRINTED { get; set; }
        public string LAST_PRINTED_BY { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryAdvice_item1> DeliveryAdvice_item1 { get; set; }
    }
}
