//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAdvice_item1
    {
        public decimal DeliveryNum { get; set; }
        public string powo { get; set; }
        public string item_num { get; set; }
        public string FACILITY { get; set; }
        public string description { get; set; }
        public Nullable<int> qty { get; set; }
        public string UOM { get; set; }
        public string DECONTIMINATED { get; set; }
        public string RTN_ADVIC_NUM { get; set; }
        public decimal ID { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<bool> IsWo1 { get; set; }
        public string IsReason { get; set; }
        public string IsVendorInstructions { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> QTY_RECV { get; set; }
    }
}
