//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIR_ADR
    {
        public int DIR_ADR_ID { get; set; }
        public string FACILITY { get; set; }
        public string TYPE { get; set; }
        public string CODE { get; set; }
        public string ADD_LINE_1 { get; set; }
        public string ADD_LINE_2 { get; set; }
        public string ADD_LINE_3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DEFAULT_ADR { get; set; }
    }
}
