//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAMSEntities1 : DbContext
    {
        public GAMSEntities1()
            : base("name=GAMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item_PurchaseOrder> Item_PurchaseOrder { get; set; }
        public virtual DbSet<Item_PurchaseOrderControlItemValue> Item_PurchaseOrderControlItemValue { get; set; }
        public virtual DbSet<Item_PurchaseOrderHistory> Item_PurchaseOrderHistory { get; set; }
        public virtual DbSet<Item_PurchaseOrderInvoice> Item_PurchaseOrderInvoice { get; set; }
        public virtual DbSet<Item_PurchaseOrderNotes> Item_PurchaseOrderNotes { get; set; }
        public virtual DbSet<Item_PurchaseOrderRequest> Item_PurchaseOrderRequest { get; set; }
    }
}
