//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_PurchaseOrderHistory
    {
        public System.Guid PurchaseOrderHistoryID { get; set; }
        public Nullable<System.Guid> PurchaseOrderID { get; set; }
        public Nullable<System.Guid> RequestID { get; set; }
        public bool IsRequestHistory { get; set; }
        public bool IsSystemGenerated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public string HistoryDetail { get; set; }
        public Nullable<System.Guid> ExceptionID { get; set; }
    
        public virtual Item_PurchaseOrder Item_PurchaseOrder { get; set; }
    }
}
