//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_PurchaseOrderRequest
    {
        public System.Guid RequestID { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
        public Nullable<System.Guid> AddressID { get; set; }
        public string VendorInstructions { get; set; }
        public int RequestReferenceNumber { get; set; }
        public Nullable<System.Guid> PurchaseOrderID { get; set; }
        public Nullable<System.Guid> EmployeeIDResponsible { get; set; }
        public Nullable<System.Guid> EmployeeIDApproval { get; set; }
        public Nullable<System.DateTime> DateApprovalConfirmed { get; set; }
        public Nullable<System.DateTime> DateApprovalRejected { get; set; }
        public string ApprovalNotes { get; set; }
        public Nullable<System.Guid> PurchaseStatusID { get; set; }
        public string DatePurchaseStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Item_PurchaseOrder Item_PurchaseOrder { get; set; }
    }
}
