//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINE_ITEM
    {
        public int LINE_ITEM_ID { get; set; }
        public int PO_ID { get; set; }
        public int REQUEST_ID { get; set; }
        public string TYPE { get; set; }
        public string STATUS { get; set; }
        public string BUYER_PART_NUM { get; set; }
        public string BUYER_PART_DESC { get; set; }
        public string VENDOR_PART_NUM { get; set; }
        public string VENDOR_PART_DESC { get; set; }
        public decimal QTY_ORDERED { get; set; }
        public decimal QTY_RECEIVED { get; set; }
        public string UOM { get; set; }
        public decimal UNIT_COST { get; set; }
        public Nullable<decimal> EST_EXTENDED_COST { get; set; }
        public Nullable<decimal> ACT_EXTENDED_COST { get; set; }
        public int PRICING_METHOD { get; set; }
        public string NOTES { get; set; }
        public string QUOTE_REQUIRED { get; set; }
        public string DISCOUNT_TYPE { get; set; }
        public string DISCOUNT { get; set; }
        public string DELIVERY { get; set; }
        public string WAREHOUSE { get; set; }
        public string ALLOC_FACILITY { get; set; }
        public string CHARGE_TO { get; set; }
        public Nullable<decimal> UNIT_CONV { get; set; }
        public string PENDING { get; set; }
        public string EXCHANGE { get; set; }
        public string SALES_ITEM { get; set; }
        public Nullable<decimal> MARKUP { get; set; }
        public Nullable<decimal> UNIT_SALE_PRICE { get; set; }
        public Nullable<decimal> EXT_SALE_PRICE { get; set; }
        public int WO_NUM { get; set; }
        public string WO_FACILITY { get; set; }
        public string SALES_TAX { get; set; }
        public string STOCK { get; set; }
        public string ESTIMATE { get; set; }
        public Nullable<decimal> FLAT_FEE { get; set; }
        public string RECEIVED { get; set; }
        public string RESPONSE { get; set; }
    }
}
