//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        public int PO_ID { get; set; }
        public string FACILITY { get; set; }
        public string PO_NUM { get; set; }
        public string PO_DATE { get; set; }
        public string PO_TIME { get; set; }
        public string PO_STATUS { get; set; }
        public string PO_NOTES { get; set; }
        public string BUYER { get; set; }
        public string ORDER_PLACED_DATE { get; set; }
        public string ORDER_PLACED_VIA { get; set; }
        public string CONFIRMATION_NUM { get; set; }
        public string ORDER_TAKER { get; set; }
        public string EST_DELIVERY_DATE { get; set; }
        public string CONTRACT_FACILITY { get; set; }
        public string CONTROL_ID { get; set; }
        public string FALSE_PO { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string SUPPLIER_NUM { get; set; }
        public int CUSTOMER_NUM { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string RDY_PRINT { get; set; }
        public string SUPPLIER_FACILITY { get; set; }
        public string BUYER_FACILITY { get; set; }
        public string REQUESTER { get; set; }
        public string REQUESTER_FACILITY { get; set; }
        public string REQUESTER_PHONE { get; set; }
        public int WO_NUM { get; set; }
        public string WO_FACILITY { get; set; }
        public string REQUEST_DEPT { get; set; }
        public string REQUEST_DEPT_FACILITY { get; set; }
        public decimal NTE { get; set; }
        public string NON_BILLABLE { get; set; }
        public int PO_NUMBER_ID { get; set; }
        public Nullable<int> DIR_ADR_ID { get; set; }
        public Nullable<decimal> PO_REQUEST { get; set; }
        public Nullable<System.DateTime> EST_DELIVERY_DATETIME { get; set; }
        public Nullable<System.DateTime> ORDER_PLACED_DATETIME { get; set; }
        public Nullable<System.DateTime> PO_DATETIME { get; set; }
        public string SHIP_TO_BILL { get; set; }
        public Nullable<double> PO_SEQ { get; set; }
    }
}
