//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Settings
    {
        public string Password { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> C_env_Animations { get; set; }
        public Nullable<bool> C_env_AutoHide_BaseBar { get; set; }
        public string C_env_Background_Color { get; set; }
        public Nullable<bool> C_env_Menu_Transparent { get; set; }
        public Nullable<bool> C_env_Widget_AirportScreen { get; set; }
        public Nullable<bool> C_env_Widget_Calender { get; set; }
        public Nullable<bool> C_env_Widget_MSG { get; set; }
        public Nullable<bool> C_env_Widget_Wiki { get; set; }
        public Nullable<bool> C_env_Widget_Notebook { get; set; }
        public Nullable<System.DateTime> C_app_WAO_Begin { get; set; }
        public Nullable<System.DateTime> C_app_WAO_End { get; set; }
        public Nullable<int> C_app_WAO_Max { get; set; }
        public Nullable<System.DateTime> C_app_EAO_Begin { get; set; }
        public Nullable<System.DateTime> C_app_EAO_End { get; set; }
        public Nullable<int> C_app_EAO_Max { get; set; }
        public Nullable<System.DateTime> C_app_PAO_Begin { get; set; }
        public Nullable<System.DateTime> C_app_PAO_End { get; set; }
        public Nullable<int> C_app_PAO_Max { get; set; }
        public Nullable<System.DateTime> C_app_INV_Begin { get; set; }
        public Nullable<System.DateTime> C_app_INV_End { get; set; }
        public Nullable<int> C_app_INV_Max { get; set; }
        public Nullable<System.DateTime> C_app_LI_Begin { get; set; }
        public Nullable<System.DateTime> C_app_LI_End { get; set; }
        public Nullable<System.DateTime> C_app_ClientInvoicing_Begin { get; set; }
        public Nullable<System.DateTime> C_app_ClientInvoicing_End { get; set; }
        public Nullable<bool> C_app_access_DA { get; set; }
        public Nullable<bool> C_app_access_PT { get; set; }
        public Nullable<bool> C_app_access_EOM { get; set; }
        public Nullable<bool> C_app_access_SCH { get; set; }
        public string C_app_access_TRVL { get; set; }
        public string C_app_isNotesPanelOpen { get; set; }
        public string NovellUserName { get; set; }
        public Nullable<bool> C_env_Widget_Clock { get; set; }
        public Nullable<bool> C_env_Widget_QisScreen { get; set; }
        public Nullable<bool> C_env_VirtualKeyboard { get; set; }
        public Nullable<bool> C_env_MenuTransparency { get; set; }
        public Nullable<bool> C_env_ApplicationTransparency { get; set; }
        public Nullable<bool> C_env_AnimationsOn { get; set; }
        public Nullable<bool> C_app_access_CPaP { get; set; }
        public Nullable<bool> C_app_access_DDS { get; set; }
        public Nullable<bool> C_app_access_TRNS { get; set; }
        public Nullable<bool> C_app_access_SafetyTester { get; set; }
        public Nullable<bool> C_app_access_DMTool { get; set; }
        public string QH_ID { get; set; }
        public Nullable<bool> C_app_access_ConsoleMngr { get; set; }
        public string C_Phone { get; set; }
        public string C_Fax { get; set; }
        public string C_Email { get; set; }
        public string C_ProfileImage { get; set; }
        public string C_Code { get; set; }
        public Nullable<int> C_app_SS_Max { get; set; }
        public Nullable<System.DateTime> EMP_StartTime { get; set; }
        public Nullable<System.DateTime> EMP_FinishTime { get; set; }
        public Nullable<int> EMP_Role { get; set; }
        public string EMP_PayRole { get; set; }
        public Nullable<decimal> EMP_PayGrade { get; set; }
        public Nullable<bool> EMP_Avail_1_Monday { get; set; }
        public Nullable<bool> EMP_Avail_1_Tuesday { get; set; }
        public Nullable<bool> EMP_Avail_1_Wednesday { get; set; }
        public Nullable<bool> EMP_Avail_1_Thursday { get; set; }
        public Nullable<bool> EMP_Avail_1_Friday { get; set; }
        public Nullable<bool> EMP_Avai_1_Saturday { get; set; }
        public Nullable<bool> EMP_Avail_1_Sunday { get; set; }
        public Nullable<bool> EMP_Avail_2_Monday { get; set; }
        public Nullable<bool> EMP_Avail_2_Tuesday { get; set; }
        public Nullable<bool> EMP_Avail_2_Wednesday { get; set; }
        public Nullable<bool> EMP_Avail_2_Thursday { get; set; }
        public Nullable<bool> EMP_Avail_2_Friday { get; set; }
        public Nullable<bool> EMP_Avail_2_Saturday { get; set; }
        public Nullable<bool> EMP_Avail_2_Sunday { get; set; }
        public string VENDOR_Number { get; set; }
        public Nullable<System.Guid> DDSUniqueIDDigitalSignaturePAO { get; set; }
        public string KPIDefaults { get; set; }
        public string C_app_PrivateInvc_Role { get; set; }
        public Nullable<bool> IS_BAN1_ENABLED { get; set; }
        public Nullable<bool> C_app_access_Unpost { get; set; }
        public string C_FileMaker_Apps_Access { get; set; }
        public Nullable<bool> C_app_ImprestStock { get; set; }
        public string NovellPhone { get; set; }
        public string NovellLocation { get; set; }
        public string NovellPosition { get; set; }
        public string NovelMobile { get; set; }
        public string RecoveryCCTR { get; set; }
        public string ExceptionDefaults { get; set; }
        public Nullable<bool> ExceptionDisplayAcknowledgedItems { get; set; }
        public string FSRVendorSupplierNumberOld { get; set; }
        public string FSRVendorSupplierNumberNew { get; set; }
        public string NovellDisplayName { get; set; }
        public string NovellCompany { get; set; }
        public string NovellDepartment { get; set; }
        public string NovellOffice { get; set; }
        public string NovellZip { get; set; }
    }
}
