//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCM
    {
        public decimal WO_NUMBER { get; set; }
        public int SEQUENCE { get; set; }
        public string PART_NUM { get; set; }
        public string PART_NAME { get; set; }
        public Nullable<decimal> PART_QTY { get; set; }
        public Nullable<decimal> PART_COST { get; set; }
        public string WORK_TYPE { get; set; }
        public Nullable<decimal> LAST_UPDATE { get; set; }
        public string WAREHOUSE { get; set; }
        public string FACILITY { get; set; }
        public string REQ_NUM { get; set; }
        public string BILLABLE { get; set; }
        public int LINE_ITEM_ID { get; set; }
        public string COST_AGAINST_CONTRACT { get; set; }
        public Nullable<int> PARTSSOURCE_LOG_ID { get; set; }
        public Nullable<System.DateTime> PartCreatedDate { get; set; }
        public string PartOrderedBy { get; set; }
        public Nullable<decimal> JOURNALED { get; set; }
        public Nullable<int> TRAVEL_INSRT_KEY { get; set; }
        public Nullable<decimal> OldWONumber { get; set; }
        public Nullable<int> MainWarehouseStock { get; set; }
    }
}
