//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCT
    {
        public decimal WO_NUMBER { get; set; }
        public decimal SEQUENCE { get; set; }
        public string EMPLOYEE { get; set; }
        public string RESPONSE { get; set; }
        public Nullable<decimal> HOURS { get; set; }
        public string ACTION { get; set; }
        public Nullable<decimal> CHG_RATE { get; set; }
        public string TIME_DONE { get; set; }
        public string DATE_DONE { get; set; }
        public Nullable<decimal> RATE_MULTI { get; set; }
        public string WORK_TYPE { get; set; }
        public string LABOR_TYPE { get; set; }
        public string COSTING_TYPE { get; set; }
        public Nullable<decimal> LAST_UPDATE { get; set; }
        public Nullable<decimal> CONTRACT_RATE { get; set; }
        public string FACILITY { get; set; }
        public string BILLABLE { get; set; }
        public Nullable<decimal> CHARGE { get; set; }
        public int LINE_ITEM_ID { get; set; }
        public Nullable<System.DateTime> DONE_DATETIME { get; set; }
        public string EMP_SRVCDEPT { get; set; }
        public string TestDevice { get; set; }
        public string TestResults { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyEmployee { get; set; }
        public Nullable<decimal> JOURNALED { get; set; }
        public Nullable<System.DateTime> LabourCreatedDate { get; set; }
    }
}
