//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WKO
    {
        public decimal WO_NUMBER { get; set; }
        public string TAG_NUMBER { get; set; }
        public string TYPE { get; set; }
        public string REQST_DATE { get; set; }
        public string REQST_TIME { get; set; }
        public string WO_TYPE { get; set; }
        public string WO_STATUS { get; set; }
        public string WO_PROBLEM { get; set; }
        public string REQUESTOR { get; set; }
        public string CONTACT { get; set; }
        public string SRVC_DEPT { get; set; }
        public string SRVC_FACILITY { get; set; }
        public Nullable<int> SPEC_CODE { get; set; }
        public string TRADE_EMP { get; set; }
        public string PROC_JOBTY { get; set; }
        public string PRIORITY { get; set; }
        public string DUE_DATE { get; set; }
        public Nullable<decimal> EST_TIME { get; set; }
        public string FREQ_UNIT { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
        public string VIEW_ONLY { get; set; }
        public string STAT_DATE { get; set; }
        public string STAT_TIME { get; set; }
        public string FAILURE { get; set; }
        public string CHG_CTR { get; set; }
        public string LOCATION { get; set; }
        public string PRINTED { get; set; }
        public string RDY_PRINT { get; set; }
        public string PURGE { get; set; }
        public string FACILITY { get; set; }
        public string WO_NOTES { get; set; }
        public string GEN_LEDGER { get; set; }
        public string FSR_TRACKING { get; set; }
        public Nullable<decimal> LAST_UPDATE { get; set; }
        public Nullable<decimal> PAGING_TRY { get; set; }
        public string TRADE_TYPE { get; set; }
        public string IMPORT { get; set; }
        public string LOCATION1 { get; set; }
        public string LOCATION2 { get; set; }
        public string LOCATION3 { get; set; }
        public string LOCATION4 { get; set; }
        public string LOCATION5 { get; set; }
        public string REGION { get; set; }
        public string ENTITY { get; set; }
        public string GL_LOCATION { get; set; }
        public string GL_COST_CTR { get; set; }
        public string GL_CODE { get; set; }
        public string PRINT_PM_NOTES { get; set; }
        public string RELEASE { get; set; }
        public string HIPAA { get; set; }
        public string CONDITION { get; set; }
        public Nullable<int> TEMPLATE_ID { get; set; }
        public string DUE_TIME { get; set; }
        public Nullable<decimal> EQU_DOWNTIME { get; set; }
        public string CLOSED { get; set; }
        public string BLD_CODE { get; set; }
        public string LOC_CODE { get; set; }
        public string RQST_CTR { get; set; }
        public Nullable<System.DateTime> DUE_DATETIME { get; set; }
        public Nullable<System.DateTime> REQST_DATETIME { get; set; }
        public Nullable<System.DateTime> STAT_DATETIME { get; set; }
        public string BTSOnlineRequestor { get; set; }
        public Nullable<decimal> WorkOrderRealDollarValue { get; set; }
        public Nullable<decimal> WorkOrderProcessedTotalChargedValue { get; set; }
        public Nullable<decimal> WorkOrderNextProcessedTotalCharge { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
