//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMS.AD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AD.IActiveDirectoryAuthentication")]
    public interface IActiveDirectoryAuthentication {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryAuthentication/wsLdapAuthenticate", ReplyAction="http://tempuri.org/IActiveDirectoryAuthentication/wsLdapAuthenticateResponse")]
        string wsLdapAuthenticate(string sUserID, string sPassword, string sLDapConnection, string domain);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IActiveDirectoryAuthentication/wsLdapAuthenticate", ReplyAction="http://tempuri.org/IActiveDirectoryAuthentication/wsLdapAuthenticateResponse")]
        System.IAsyncResult BeginwsLdapAuthenticate(string sUserID, string sPassword, string sLDapConnection, string domain, System.AsyncCallback callback, object asyncState);
        
        string EndwsLdapAuthenticate(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActiveDirectoryAuthenticationChannel : GAMS.AD.IActiveDirectoryAuthentication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsLdapAuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public wsLdapAuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActiveDirectoryAuthenticationClient : System.ServiceModel.ClientBase<GAMS.AD.IActiveDirectoryAuthentication>, GAMS.AD.IActiveDirectoryAuthentication {
        
        private BeginOperationDelegate onBeginwsLdapAuthenticateDelegate;
        
        private EndOperationDelegate onEndwsLdapAuthenticateDelegate;
        
        private System.Threading.SendOrPostCallback onwsLdapAuthenticateCompletedDelegate;
        
        public ActiveDirectoryAuthenticationClient() {
        }
        
        public ActiveDirectoryAuthenticationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActiveDirectoryAuthenticationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActiveDirectoryAuthenticationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActiveDirectoryAuthenticationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<wsLdapAuthenticateCompletedEventArgs> wsLdapAuthenticateCompleted;
        
        public string wsLdapAuthenticate(string sUserID, string sPassword, string sLDapConnection, string domain) {
            return base.Channel.wsLdapAuthenticate(sUserID, sPassword, sLDapConnection, domain);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginwsLdapAuthenticate(string sUserID, string sPassword, string sLDapConnection, string domain, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginwsLdapAuthenticate(sUserID, sPassword, sLDapConnection, domain, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndwsLdapAuthenticate(System.IAsyncResult result) {
            return base.Channel.EndwsLdapAuthenticate(result);
        }
        
        private System.IAsyncResult OnBeginwsLdapAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sUserID = ((string)(inValues[0]));
            string sPassword = ((string)(inValues[1]));
            string sLDapConnection = ((string)(inValues[2]));
            string domain = ((string)(inValues[3]));
            return this.BeginwsLdapAuthenticate(sUserID, sPassword, sLDapConnection, domain, callback, asyncState);
        }
        
        private object[] OnEndwsLdapAuthenticate(System.IAsyncResult result) {
            string retVal = this.EndwsLdapAuthenticate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnwsLdapAuthenticateCompleted(object state) {
            if ((this.wsLdapAuthenticateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.wsLdapAuthenticateCompleted(this, new wsLdapAuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void wsLdapAuthenticateAsync(string sUserID, string sPassword, string sLDapConnection, string domain) {
            this.wsLdapAuthenticateAsync(sUserID, sPassword, sLDapConnection, domain, null);
        }
        
        public void wsLdapAuthenticateAsync(string sUserID, string sPassword, string sLDapConnection, string domain, object userState) {
            if ((this.onBeginwsLdapAuthenticateDelegate == null)) {
                this.onBeginwsLdapAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginwsLdapAuthenticate);
            }
            if ((this.onEndwsLdapAuthenticateDelegate == null)) {
                this.onEndwsLdapAuthenticateDelegate = new EndOperationDelegate(this.OnEndwsLdapAuthenticate);
            }
            if ((this.onwsLdapAuthenticateCompletedDelegate == null)) {
                this.onwsLdapAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnwsLdapAuthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginwsLdapAuthenticateDelegate, new object[] {
                        sUserID,
                        sPassword,
                        sLDapConnection,
                        domain}, this.onEndwsLdapAuthenticateDelegate, this.onwsLdapAuthenticateCompletedDelegate, userState);
        }
    }
}
